# Generated by Django 4.0.1 on 2022-03-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(blank=True, max_length=30, null=True)),
                ('is_deleted', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'states',
                'managed': True,
            },
        ),
    ]
