# Generated by Django 4.0.1 on 2022-01-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbase',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
