# Generated by Django 4.0.1 on 2022-01-23 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_userbase_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userbase',
            options={'verbose_name': 'Konto', 'verbose_name_plural': 'Konta'},
        ),
    ]
