# Generated by Django 4.0.1 on 2022-08-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customer_nip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='nip',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
