# Generated by Django 4.0.1 on 2022-01-28 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('length', models.DecimalField(decimal_places=0, max_digits=4)),
                ('width', models.DecimalField(decimal_places=0, max_digits=4)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_material', to='order.material')),
            ],
        ),
    ]
