# Generated by Django 4.0.1 on 2022-03-09 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractor',
            options={'verbose_name': 'Kontrahent', 'verbose_name_plural': 'Kontrahenci'},
        ),
    ]
