# Generated by Django 4.0.1 on 2022-01-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
