# Generated by Django 4.0.1 on 2022-02-12 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionstock',
            name='production',
        ),
        migrations.AddField(
            model_name='productionstock',
            name='ProductionMaterial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stock.productionmaterial'),
            preserve_default=False,
        ),
    ]
