# Generated by Django 4.0.1 on 2022-02-09 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='production',
            old_name='material',
            new_name='materials',
        ),
    ]
