# Generated by Django 4.0.1 on 2022-02-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='materials',
            field=models.ManyToManyField(to='order.Material'),
        ),
        migrations.AddField(
            model_name='production',
            name='stocks',
            field=models.ManyToManyField(to='stock.Stock'),
        ),
    ]
