# Generated by Django 4.0.1 on 2022-02-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionstock',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productionstockin',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
