# Generated by Django 4.0.1 on 2022-02-06 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('stock', '0002_production_materials_production_stocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='reduce_material',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.material'),
        ),
    ]
