# Generated by Django 4.0.1 on 2022-02-21 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('stock', '0002_goodsreceivednote_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreceivednote',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='order.material'),
        ),
    ]
