# Generated by Django 4.0.1 on 2022-02-09 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_frezy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Frezy',
            new_name='Cutter',
        ),
    ]
