# Generated by Django 4.0.1 on 2022-02-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_grnmaterial_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grnmaterial',
            name='area',
            field=models.FloatField(default=0.0),
        ),
    ]
