# Generated by Django 4.0.1 on 2022-03-14 10:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_contractor_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceivednote',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Niezatwierdzone'), (1, 'Zatwierdzone')], default=0),
        ),
        migrations.AddField(
            model_name='grnmaterial',
            name='price_gross',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='grnmaterial',
            name='vat',
            field=models.SmallIntegerField(choices=[(0, '8%'), (1, '23%')], default=1),
        ),
    ]
