# Generated by Django 4.0.1 on 2022-02-09 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('stock', '0002_rename_material_production_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='materials',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.material'),
        ),
    ]
