# Generated by Django 4.0.1 on 2022-03-23 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_remove_stock_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stock.warehouse'),
            preserve_default=False,
        ),
    ]
