# Generated by Django 4.0.1 on 2022-02-18 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_productionstock_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionmaterial',
            name='comments',
        ),
        migrations.AlterField(
            model_name='production',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'w trakcie'), (1, 'zakończone')], default=0),
        ),
        migrations.CreateModel(
            name='ProductionComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('productionMaterial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='stock.productionmaterial')),
            ],
        ),
    ]
