# Generated by Django 4.0.1 on 2022-01-30 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_warehouse_name'),
        ('stock', '0003_alter_stock_material'),
    ]

    operations = [
    ]
