# Generated by Django 4.0.1 on 2022-03-14 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_goodsreceivednote_status_grnmaterial_price_gross_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grnmaterial',
            old_name='price_gross',
            new_name='price_net',
        ),
    ]
