# Generated by Django 4.0.1 on 2022-02-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_rename_frezy_cutter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutter',
            name='forSharpening',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cutter',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cutter',
            name='toBuy',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
