# Generated by Django 4.0.1 on 2022-02-21 15:35

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('stock', '0003_alter_goodsreceivednote_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsreceivednote',
            name='quantity',
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='area',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.000'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='goodsreceivednote',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.material'),
        ),
    ]
