# Generated by Django 4.0.1 on 2022-03-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='comment',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
