# Generated by Django 4.0.1 on 2022-02-12 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_rename_productionmaterial_productionstock_productionmaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionstock',
            name='productionMaterial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='stock.productionmaterial'),
        ),
    ]
