# Generated by Django 4.0.1 on 2022-02-28 12:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_grnmaterial_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grnmaterial',
            name='area',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.000'), max_digits=10),
        ),
    ]
