# Generated by Django 4.0.1 on 2022-02-15 20:36

from django.db import migrations, models
import django.db.models.deletion
import order.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_material_name_alter_material_quantity_and_more'),
        ('stock', '0004_alter_productionstock_productionmaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionStockIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', order.models.IntegerRangeField()),
                ('width', order.models.IntegerRangeField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.material')),
                ('productionMaterial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.productionmaterial')),
            ],
        ),
    ]
