# Generated by Django 4.0.1 on 2022-03-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_rename_price_gross_grnmaterial_price_net'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceivednote',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
