# Generated by Django 4.0.1 on 2022-02-28 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_grnmaterial_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractor',
            name='address',
        ),
    ]
