# Generated by Django 4.0.1 on 2022-01-30 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('stock', '0004_merge_0002_warehouse_name_0003_alter_stock_material'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='Warehouse',
            new_name='warehouse',
        ),
        migrations.AlterField(
            model_name='stock',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='order.material'),
        ),
    ]
