# Generated by Django 4.0.1 on 2022-02-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_remove_goodsreceivednote_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceivednote',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
