# Generated by Django 4.0.1 on 2022-03-16 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_payment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cash',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='stock.cash'),
        ),
    ]
