# Generated by Django 4.0.1 on 2022-02-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_cutter_forsharpening_alter_cutter_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutter',
            name='forSharpening',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cutter',
            name='toBuy',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
