# Generated by Django 4.0.1 on 2022-02-06 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_rename_reduce_material_production_reducematerial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='production',
            old_name='reduceMaterial',
            new_name='materialUsed',
        ),
    ]
