# Generated by Django 4.0.1 on 2022-02-01 15:46

from django.db import migrations
import order.models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_rename_warehouse_stock_warehouse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='length',
            field=order.models.IntegerRangeField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='width',
            field=order.models.IntegerRangeField(),
        ),
    ]
