# Generated by Django 4.0.1 on 2022-02-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_goodsreceivednote_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreceivednote',
            name='quantity',
            field=models.CharField(max_length=255),
        ),
    ]
