# Generated by Django 4.0.1 on 2022-02-16 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_productionstockin'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionmaterial',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
