# Generated by Django 4.0.1 on 2022-03-14 15:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_cash'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cash',
            options={'verbose_name': 'Kasa', 'verbose_name_plural': 'Kasy'},
        ),
        migrations.AddField(
            model_name='cash',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
