# Generated by Django 4.0.1 on 2022-02-16 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_productionmaterial_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Przygotowywanie'), (1, 'Zakończone')], default=0),
        ),
    ]
