# Generated by Django 4.0.1 on 2022-02-06 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('stock', '0006_remove_production_materials_production_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='order.material'),
        ),
    ]
