# Generated by Django 4.0.1 on 2022-02-06 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('stock', '0007_alter_stock_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.material'),
        ),
        migrations.AlterField(
            model_name='production',
            name='stocks',
            field=models.ManyToManyField(blank=True, null=True, to='stock.Stock'),
        ),
    ]
