# Generated by Django 4.0.1 on 2022-08-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_stock_rack'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='rack_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
