# Generated by Django 4.0.1 on 2022-02-22 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('stock', '0007_remove_goodsreceivednote_material_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsreceivednote',
            name='material',
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='material',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.material'),
            preserve_default=False,
        ),
    ]
