# Generated by Django 4.0.1 on 2022-03-17 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_alter_payment_options_payment_cash_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='cash',
        ),
        migrations.DeleteModel(
            name='Cash',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
