# Generated by Django 4.0.1 on 2022-02-03 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_production'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='stock',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='stock.stock'),
        ),
    ]
