# Generated by Django 4.0.1 on 2022-02-22 15:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_remove_goodsreceivednote_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreceivednote',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.000'), max_digits=10),
        ),
    ]
