# Generated by Django 4.0.1 on 2022-08-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_stock_rack_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='rack_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
