# Generated by Django 4.0.1 on 2022-02-22 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_alter_goodsreceivednote_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsreceivednote',
            name='area',
        ),
    ]
