# Generated by Django 4.0.1 on 2023-04-11 15:23

from django.db import migrations, models
import stock.models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_alter_stock_rack_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='material_group_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='thickness',
            field=stock.models.IntegerRangeField(null=True),
        ),
    ]
