# Generated by Django 4.0.1 on 2022-02-06 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import order.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0009_alter_production_stocks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Karta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=255)),
                ('comments', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.material')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Spad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', order.models.IntegerRangeField()),
                ('width', order.models.IntegerRangeField()),
                ('karta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.karta')),
            ],
        ),
        migrations.CreateModel(
            name='Formatka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', order.models.IntegerRangeField()),
                ('width', order.models.IntegerRangeField()),
                ('karta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.karta')),
            ],
        ),
    ]
