# Generated by Django 4.0.1 on 2022-02-06 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_karta_spad_formatka'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formatka',
            name='karta',
        ),
        migrations.RemoveField(
            model_name='production',
            name='stocks',
        ),
        migrations.RemoveField(
            model_name='spad',
            name='karta',
        ),
        migrations.AddField(
            model_name='formatka',
            name='production',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.production'),
        ),
        migrations.AddField(
            model_name='spad',
            name='production',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.production'),
        ),
        migrations.DeleteModel(
            name='Karta',
        ),
    ]
