# Generated by Django 4.0.1 on 2022-02-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('stock', '0010_remove_goodsreceivednote_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsreceivednote',
            name='material',
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='material',
            field=models.ManyToManyField(to='order.Material'),
        ),
    ]
