# Generated by Django 4.0.1 on 2023-04-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_material_material_group_name_material_thickness'),
    ]

    operations = [
        migrations.AddField(
            model_name='gender',
            name='code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
