# Generated by Django 4.0.1 on 2023-04-11 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_gender_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='material_group_name',
        ),
    ]
