# Generated by Django 4.0.1 on 2022-02-07 13:00

from django.db import migrations, models
import django.db.models.deletion
import order.models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_production_stocks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', order.models.IntegerRangeField()),
                ('width', order.models.IntegerRangeField()),
                ('material', models.CharField(max_length=200)),
                ('production', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.production')),
            ],
        ),
        migrations.DeleteModel(
            name='Formatka',
        ),
    ]
