# Generated by Django 4.0.1 on 2022-02-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_productionstock_delete_formatka'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionstock',
            name='production',
        ),
        migrations.AddField(
            model_name='production',
            name='productionStocks',
            field=models.ManyToManyField(blank=True, to='stock.ProductionStock'),
        ),
    ]
