# Generated by Django 4.0.1 on 2022-02-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_remove_productionstock_production_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='productionStocks',
            field=models.ManyToManyField(blank=True, related_name='stockss', to='stock.ProductionStock'),
        ),
    ]
