# Generated by Django 4.0.1 on 2022-02-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_alter_production_productionstocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='productionStocks',
            field=models.ManyToManyField(blank=True, to='stock.ProductionStock'),
        ),
    ]
