# Generated by Django 4.0.1 on 2022-03-29 11:01

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0007_productionorder_description'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price_net', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('price_gross', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('vat', models.SmallIntegerField(choices=[(0, '0%'), (1, '8%'), (2, '23%')], default=2)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.material')),
                ('ms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.materialservices')),
            ],
        ),
    ]
