# Generated by Django 4.0.1 on 2022-03-29 14:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_remove_offer_ms_offer_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='services',
        ),
        migrations.AddField(
            model_name='offer',
            name='price_net_unit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='offer',
            name='serivces',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='material',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='offer',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
