# Generated by Django 4.0.1 on 2022-03-29 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_remove_offer_services_offer_price_net_unit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='serivces',
            new_name='services',
        ),
    ]
