# Generated by Django 4.0.1 on 2022-03-29 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0004_rename_serivces_offer_services'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='material',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='services',
        ),
    ]
