# Generated by Django 4.0.1 on 2022-03-30 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('offer', '0005_rename_material_offer_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.customer'),
            preserve_default=False,
        ),
    ]
