# Generated by Django 4.0.1 on 2022-03-30 09:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0006_offer_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('price_net_unit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('price_net', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('price_gross', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('vat', models.SmallIntegerField(choices=[(0, '0%'), (1, '8%'), (2, '23%')], default=2)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='offer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='price_gross',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='price_net',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='price_net_unit',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='vat',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='vat_amount',
        ),
        migrations.AddField(
            model_name='offer',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
