# Generated by Django 4.0.1 on 2022-03-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0007_offeritems_remove_offer_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='title',
        ),
        migrations.AddField(
            model_name='offer',
            name='number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
