# Generated by Django 4.0.1 on 2022-04-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
