# Generated by Django 4.0.1 on 2022-03-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productioncomments',
            name='units',
        ),
        migrations.AddField(
            model_name='services',
            name='units',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
