# Generated by Django 4.0.1 on 2022-03-01 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('production', '0002_customer_company_alter_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.material'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='services',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production.services'),
        ),
    ]
