# Generated by Django 4.0.1 on 2022-03-20 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_alter_productionmaterial_waste_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionmaterial',
            name='waste_field',
        ),
    ]
