# Generated by Django 4.0.1 on 2022-03-21 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('production', '0004_remove_productionmaterial_waste_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionmaterial',
            name='material',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='order.material'),
        ),
    ]
