# Generated by Django 4.0.1 on 2023-04-13 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_stock_gender'),
        ('production', '0004_production_updated_at_productionorder_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialservices',
            name='gender',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.gender'),
        ),
    ]
