# Generated by Django 4.0.1 on 2022-03-01 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('production', '0004_remove_productionorder_material_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionorder',
            name='material',
        ),
        migrations.RemoveField(
            model_name='productionorder',
            name='services',
        ),
        migrations.CreateModel(
            name='MaterialServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.material')),
                ('productionorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.productionorder')),
                ('services', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production.services')),
            ],
        ),
    ]
