# Generated by Django 4.0.1 on 2022-03-22 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_alter_productionmaterial_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionorder',
            name='attachments',
        ),
    ]
