# Generated by Django 4.0.1 on 2022-03-01 15:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_remove_productionorder_material_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'usługa', 'verbose_name_plural': 'usługi'},
        ),
        migrations.RemoveField(
            model_name='materialservices',
            name='quantity',
        ),
        migrations.AddField(
            model_name='materialservices',
            name='area',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.000'), max_digits=10),
        ),
    ]
