# Generated by Django 4.0.1 on 2022-03-03 09:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_alter_services_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialservices',
            name='total_price',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='materialservices',
            name='area',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10),
        ),
    ]
