# Generated by Django 4.0.1 on 2022-03-03 13:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_materialservices_total_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialservices',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='services',
            name='price_gross',
        ),
        migrations.AddField(
            model_name='materialservices',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
