# Generated by Django 4.0.1 on 2022-03-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_alter_production_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialservices',
            name='transport',
            field=models.BooleanField(default=0),
        ),
    ]
