# Generated by Django 4.0.1 on 2022-03-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_materialservices_transport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialservices',
            name='transport',
        ),
        migrations.AddField(
            model_name='productionorder',
            name='status',
            field=models.SmallIntegerField(choices=[('zmień status', 'zmień status'), (0, 'Przygotowywanie'), (1, 'Oczekuję'), (2, 'W trakcie'), (3, 'Zakończone')], default=0),
        ),
    ]
