# Generated by Django 4.0.1 on 2022-03-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0012_alter_production_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Przygotowywanie'), (1, 'Oczekuję'), (2, 'W trakcie'), (3, 'Zakończone')], default=0),
        ),
    ]
