# Generated by Django 4.0.1 on 2022-03-14 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0013_alter_productionorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='production.customer'),
            preserve_default=False,
        ),
    ]
