# Generated by Django 4.0.1 on 2022-03-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0014_production_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='settlement',
            field=models.BooleanField(default=False),
        ),
    ]
