# Generated by Django 4.0.1 on 2022-03-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0015_production_settlement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='settlement',
        ),
        migrations.AddField(
            model_name='productionorder',
            name='settlement',
            field=models.BooleanField(default=False),
        ),
    ]
