# Generated by Django 4.0.1 on 2022-03-14 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customer'),
        ('production', '0017_customer_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.customer'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.customer'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
