# Generated by Django 4.0.1 on 2022-03-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
