# Generated by Django 4.0.1 on 2022-03-22 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0003_payment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
    ]
