# Generated by Django 4.0.1 on 2022-03-22 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0006_payment_id_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='id_number',
        ),
    ]
