# Generated by Django 4.0.1 on 2022-03-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0007_remove_payment_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='id_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
