# Generated by Django 4.0.1 on 2022-01-19 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import randomslugfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Milling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('milling_side', models.CharField(blank=True, choices=[('----', ''), ('po krótkim', 'po krótkim'), ('po długim', 'po długim')], default='----', max_length=30)),
            ],
            options={
                'verbose_name': 'frez',
                'verbose_name_plural': 'frezy',
            },
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'wzór',
                'verbose_name_plural': 'wzory',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('slug', randomslugfield.fields.RandomSlugField(blank=True, editable=False, exclude_lower=True, exclude_upper=True, exclude_vowels=True, length=7, max_length=7, unique=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'Oczekuję'), (1, 'W trakcie'), (2, 'Zakończone')], default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'zamówienie',
                'verbose_name_plural': 'zamówienia',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveSmallIntegerField()),
                ('lenght', models.PositiveSmallIntegerField()),
                ('milling', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.milling')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.order')),
                ('pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.pattern')),
            ],
            options={
                'verbose_name': 'formatka',
                'verbose_name_plural': 'formatki',
            },
        ),
    ]
