# Generated by Django 4.0.1 on 2022-02-01 15:43

from django.db import migrations
import order.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='length',
            field=order.models.IntegerRangeField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='width',
            field=order.models.IntegerRangeField(),
        ),
    ]
