# Generated by Django 4.0.1 on 2022-01-19 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MillingSide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milling_side', models.CharField(blank=True, choices=[('----', ''), ('po krótkim', 'po krótkim'), ('po długim', 'po długim')], default='----', max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='milling',
            name='milling_side',
        ),
        migrations.AlterField(
            model_name='item',
            name='order',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.order'),
        ),
        migrations.AddField(
            model_name='item',
            name='millingSide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.millingside'),
        ),
    ]
