# Generated by Django 4.0.1 on 2022-01-26 16:26

from django.db import migrations
import order.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='lenght1',
            field=order.models.CustomBooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='lenght2',
            field=order.models.CustomBooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='width1',
            field=order.models.CustomBooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='width2',
            field=order.models.CustomBooleanField(default=1),
        ),
    ]
