# Generated by Django 4.0.1 on 2022-01-26 16:27

from django.db import migrations
import order.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_item_lenght1_alter_item_lenght2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='lenght1',
            field=order.models.CustomBooleanField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='lenght2',
            field=order.models.CustomBooleanField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='width1',
            field=order.models.CustomBooleanField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='width2',
            field=order.models.CustomBooleanField(),
        ),
    ]
