# Generated by Django 4.0.1 on 2022-01-27 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_attachment_attachment_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='order',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
    ]
