# Generated by Django 4.0.1 on 2022-02-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_item_length_alter_item_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='quantity',
            field=models.SmallIntegerField(default=1),
        ),
    ]
