# Generated by Django 4.0.1 on 2022-01-19 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_millingside_remove_milling_milling_side_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='millingSide',
        ),
        migrations.AddField(
            model_name='item',
            name='milling_side',
            field=models.CharField(blank=True, choices=[('----', ''), ('po krótkim', 'po krótkim'), ('po długim', 'po długim')], default='----', max_length=30),
        ),
        migrations.DeleteModel(
            name='MillingSide',
        ),
    ]
