# Generated by Django 4.0.1 on 2022-01-19 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_item_millingside_item_milling_side_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='milling_side',
            field=models.CharField(blank=True, choices=[('po krótkim', 'po krótkim'), ('po długim', 'po długim')], max_length=30),
        ),
    ]
