# Generated by Django 4.0.1 on 2022-01-21 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_item_quantity_alter_item_milling_side'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='milling',
        ),
        migrations.RemoveField(
            model_name='item',
            name='milling_side',
        ),
        migrations.RemoveField(
            model_name='item',
            name='pattern',
        ),
        migrations.AlterField(
            model_name='item',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.order'),
        ),
    ]
