# Generated by Django 4.0.1 on 2022-01-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_attachment_date_created_alter_attachment_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[('zmień status', 'zmień status'), (0, 'Przygotowywanie'), (1, 'Oczekuję'), (2, 'W trakcie'), (3, 'Zakończone')], default=0),
        ),
    ]
