# Generated by Django 4.0.1 on 2022-01-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_item_milling_remove_item_milling_side_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='width',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
    ]
