# Generated by Django 4.0.1 on 2022-01-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='length1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='length2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='width1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='width2',
            field=models.BooleanField(default=False),
        ),
    ]
