# Generated by Django 4.0.1 on 2022-01-22 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_item_length1_item_length2_item_width1_item_width2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='length1',
            new_name='lenght1',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='length2',
            new_name='lenght2',
        ),
    ]
